# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements first and install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source
COPY server.py app.py ./

# Copy additional modules and files if any (e.g., __pycache__ is not needed)
# Set default working directory
WORKDIR /app

# No CMD: the MCP harness will run via stdio as configured
